### ISSUE TITLE
Dodajte prikaz vise lopti odjednom

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG094-avoid-responsibility#2]
Dodajte prikaz vise lopti odjednom - na razlicitim udaljenostima od igraca. Mozete da napravite niz lopti gde kako koja prodje igraca (potpuno prodje - da se vise ne vidi), reciklirate je i stavite na kraj.

**Comment by mi15104** [comment]
Lopte se sada dodaju na proizvoljan nacin i uvek je bar jedna linija slobodna da bi igrac imao gde da se skloni.
